FROM jenkins/jenkins

USER root
#Docker installation
RUN apt-get update && apt-get -y install ca-certificates \
curl \
gnupg \
apt-transport-https \
software-properties-common

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN apt update && apt-get -y install docker-ce docker-ce-cli
#Docker compose installation
RUN apt-get -y install docker-compose-plugin
RUN usermod -aG docker jenkins
USER jenkins
