version: "3.9"
services:
        jenkins:
                container_name: jenkins
                image: jenkins/jenkins
                build:
                        context: .
                        dockerfile: Dockerfile-Jenkins
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - $PWD/jenkins_backup_data/jenkins_home:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock
