pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'jenkins-docker-apache/scripts/build.sh'
            }
        }
        stage('Backup') {
            steps {
                sh 'jenkins-docker-apache/scripts/backup_vm.sh'
            }
        }
        stage('Deploy'){
	       steps {
                sh 'jenkins-docker-apache/scripts/deploy_vm.sh'
	       }
	   }
    }
}
