pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh './scripts/build.sh'
            }
        }
        stage('Backup') {
            steps {
                sh './scripts/backup_vm.sh'
            }
        }
        stage('Deploy'){
	       steps {
                sh './scripts/deploy_vm.sh'
	       }
	   }
    }
}
