version: "3.9"

services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-wp
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    networks:
      - wp-net

  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
        - db-data:/var/lib/mysql
    networks:
      - wp-net

  nginx:
    depends_on:
            - wordpress
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-db-resources/nginx.conf:/etc/nginx/nginx.conf
      - ./wp-resources/ssl/:/etc/nginx/ssl/
    networks:
      - wp-net

networks:
    wp-net:

volumes:
    db-data:

