FROM ubuntu:latest

RUN apt-get update && apt-get install -y mysql-server

RUN sed -i 's/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf

COPY nginx-db-resources/init-db.sh /tmp/init-db.sh
RUN chmod +x /tmp/init-db.sh

EXPOSE 3306

CMD ["/tmp/init-db.sh"]
