pipeline {
    agent any
    tools {
        maven 'MAVEN386'
    }
    stages {
        stage('App pull') {
            steps {
                sh 'jenkins-docker-maven/scripts/pull-app.sh'
            }
        }
        stage('Test') {
            steps {
                dir('jenkins-docker-maven/app'){
                    sh '''
			mkdir target
			#mvn clean
			#mvn test
		       '''
                }
            }
        }
        stage('App build') {
            steps {
                sh 'jenkins-docker-maven/scripts/build-app.sh'
            }
        }
        stage('Image Build'){
               steps {
                sh 'jenkins-docker-maven/scripts/build-image.sh'
            }
        }
        stage('Image Push'){
               steps {
                sh 'jenkins-docker-maven/scripts/push.sh $BUILD_NUMBER'
            }
        }
    }
}
