localhost ansible_connection=local
web01 ansible_host=192.168.77.101
web02 ansible_host=192.168.77.103
java01 ansible_host=192.168.77.102

[appgrp]
java01

[webgrp]
web01
web02

[uwebgrp]
web01

[cwebgrp]
web02

[localgrp]
localhost

[dockergrp]
java01
localhost

[containergrp]
java01

[vms:children]
appgrp
webgrp

[vms:vars]
ansible_ssh_private_key_file=/home/vagrant/.ssh/id_rsa
ansible_user=vagrant
