pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                docker compose -f web/docker-compose-alpine.yaml up -d --force-recreate
                docker cp alpine-web:/mnt/webfiles/data data/
                mv data/data data/webfiles
                '''
            }
        }
        stage('Backup') {
            steps {
                sh './scripts/backup_vm.sh'
            }
        }
        stage('Deploy'){
	       steps {
                sh './scripts/deploy_vm.sh'
	       }
	   }
    }
}
